### ISSUE TITLE
Calling my node server with option `--expose-gc` causes error in remotedev

### ISSUE THREAD

**Issue by hyperh** [zalmoxisus/remotedev-server#53]
When I run my app server with the following:

```
npm run babel-node -- server/index.js --expose-gc
```

I get this error:

```
1514932055651 - Origin: WorkerCluster (PID 5636)
   [Error] ProcessExitError: WorkerCluster exited with code: 1
    at EventEmitter.SocketCluster._handleWorkerClusterExit (/Users/hl/development/BrainFM_New/node_modules/socketcluster/index.js:571:17)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

  error: unknown option `--expose-gc'
```

I've tested removing the line

```
remotedev({ hostname: 'localhost', port: 8000 });
```
from my code and it fixes the problem which means `remotedev` is definitely the issue here. However, I would like to keep that line in.

**Comment by zalmoxisus** [comment]
According to https://github.com/SocketCluster/socketcluster/issues/105 it will work only if `--expose-gc` is before `server/index.js`, otherwise it is interpreted as socketcluster option.
